FROM python:3.10-slim

WORKDIR /app

COPY mission-control/api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY mission-control/api/ .

CMD ["fastapi", "run", "main.py", "--port", "8000"]
