"""asset_scene_fields

Revision ID: 856451ef2c24
Revises: 47fb2508dfd4
Create Date: 2026-07-14 09:25:31.063718
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '856451ef2c24'
down_revision: Union[str, None] = '47fb2508dfd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('scene_number', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'thumbnail_url')
    op.drop_column('assets', 'scene_number')
    # ### end Alembic commands ###
